// <auto-generated />
namespace Stopwatch.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Member : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Member));
        
        string IMigrationMetadata.Id
        {
            get { return "201401300039095_Member"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
